PUT http://localhost:5000/superhumans/1
Content-Type: application/json

{
  "nickname": "Ironwolf1",
  "realName": "Wolf Aufovich1",
  "originDescription": "Forest wolf1...",
  "catchPhrase": "Catchphrase 2"
}
